import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import goku from '../public/goku.png'
import { Icon } from '@iconify/react';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Naufal Azim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header Start  */}

      <header className='bg-transparent absolute top-5 left-0 w-full flex items-center z-10'>
        <div className='container'>

          <div className='flex items-center justify-between relative'>
            <div className='px-4'>
              <h1 className='tracking-wide font-semibold text-xl text-primary block'><a href='#home'>NA</a></h1>
            </div>

           <div>
            <ul className='flex flex-wrap space-x-4 text-2xl'>
              <li> <a href='https://www.linkedin.com/in/mnaufalazim/' target="_blank"><Icon icon="akar-icons:linkedin-box-fill" /></a></li>
              <li><a href='https://github.com/naufalazim' target="_blank"><Icon icon="akar-icons:github-fill" /></a></li>
              <li><a href='mailto:naufal.azim@outlook.com' target="_blank" ><Icon icon="clarity:email-solid" /></a></li>
            </ul>
           </div>


          </div>
        </div>
      </header>


      {/* Header End  */}



      {/* Hero Section Start  */}
      <section id='home'>

        <div className='container pt-36'>
          <div className='flex flex-wrap'>

            <div className='w-full self-center px-4 lg:w-1/2'>
              <h1 className='text-based font-bold md:text-xl lg:text-2xl'>Hello there 👋🏻, I'm <span className='block text-sky-700 text-4xl mt-1 lg:text-5xl'>Naufal Azim</span></h1>
                <h2 className='font-medium text-slate-500 text-lg mb-5 lg:text-2xl'> <span className='text-pink-500'>Computer Science</span> Student at <span className=''>UPNM 🇲🇾</span></h2>
                <p className='font-medium text-slate-500 mb-10 leading-relaxed text\'>
                  I love to build stuff and explore the new technology for fun and to learn new things.
                  <span className=' text-slate-500'> I've been participating in some hackathons and competitions related to web development
                  and programming.</span>
                  <span className='block text-slate-800'>Indie hacker to be! <span className='text-2xl'>🚀</span></span>
                </p>
                <button className="rounded-full border-2 border-slate-900 py-2 px-4 hover:shadow-lg hover:bg-black hover:text-white hover:opacity-80 transition duration-300 ease-in-out"><a href='/resume.pdf' download="resume.pdf">My Resume</a></button>
            </div>

            <div className='w-full self-end px-4 lg:w-1/2'>
              <div className=' relative mt-10 lg:mt-9 lg:right-0'>
                <img src='/naufal.png' alt='Naufal Azim' width="400" height="400" className='max-w-full mx-auto rounded-full'></img>
                <span className='absolute bottom-0 -z-10 left-1/2 -translate-x-1/2 md:scale-125'>
                    <svg width="400" height="400" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
                    <path fill="#FF0066" d="M34.7,-38.7C47.9,-30.2,63.7,-22.1,67.7,-10.3C71.8,1.6,64.2,17.1,54.8,29.8C45.3,42.5,33.9,52.2,19.8,59.6C5.7,67,-11.2,72.1,-25.3,67.7C-39.4,63.4,-50.7,49.6,-55.8,35C-60.9,20.4,-59.7,5.1,-59.8,-13.3C-59.8,-31.6,-61,-52.9,-51.2,-62C-41.5,-71,-20.7,-67.9,-5,-61.9C10.7,-56,21.5,-47.2,34.7,-38.7Z" 
                    transform="translate(100 100) scale(1.1)"/>
                  </svg>
                </span>
              </div>
            </div>

          </div>
        </div>
      </section>
      {/* Hero Section End  */}
  






    </div>
  )
}
